---
- hosts: ansclient
#  remote_user: root
  tasks:
    - name: httpd install
      yum: name=httpd state=latest
    - name: enable httpd service
      service: name=httpd state=started enabled=yes
  become_user: root
  become: true
