---
- hosts: ansclient
#  remote_user: root
  tasks:
    - name: mariadb-server install
      yum: name=mariadb-server state=latest
    - name: enable httpd service
      service: name=mariadb state=started enabled=yes
  become_user: root
  become: true
